version: '3.9'

services:
  app:
    build: .
    container_name: docX
    ports:
      - "8000:8000"  
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:v1.7.3
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
