version: '3.9'

services:
  fastapi:
    build: .
    container_name: fastapi-app
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - qdrant

  streamlit:
    build: .
    container_name: streamlit-app
    command: streamlit run src/streamlit_app.py 
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - fastapi

  # qdrant:
  #   image: qdrant/qdrant:v1.7.3
  #   container_name: qdrant
  #   ports:
  #     - "6333:6333"
  #   volumes:
  #     - qdrant_data:/qdrant/storage

# volumes:
#   qdrant_data:
